server:
  port: 9092

# 数据库配置信息
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3336/second?useUnicode=true&characterEncoding=utf-8&serverTimezone=PRC&useSSL=false
    username: sckr
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379

we-chat:
  app-id: wx01ff1f0e500c1b37
  secret: ae8b4576bad22e9a37edb0ef50c2181b


